#!/sbin/busybox sh

export BOOTREC_EVENT_NODE="/dev/input/event11 c 13 75"
export BOOTREC_EVENT="/dev/input/event11"
export BOOTREC_LED_RED="/sys/devices/i2c-10/10-0047/leds/LED1_R/brightness"
export BOOTREC_LED_GREEN="/sys/devices/i2c-10/10-0047/leds/LED1_G/brightness"
export BOOTREC_LED_BLUE="/sys/devices/i2c-10/10-0047/leds/LED1_B/brightness"
export BOOTREC_FOTA_NODE="/dev/block/mmcblk0p11 b 179 11"
export BOOTREC_FOTA="/dev/block/mmcblk0p11"
